import { createRoot } from 'react-dom/client';
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import { open, save as saveDialog } from '@tauri-apps/plugin-dialog';
import { readTextFile, writeTextFile } from '@tauri-apps/plugin-fs';
import { Bot, Check, ChevronDown, Copy, Download, FilePlus2, History, Menu, MessageSquare, Moon, Paperclip, Plus, Search, Send, Settings, Sparkles, Sun, Trash2, Upload, UserRound, X } from 'lucide-react';

type Page = 'home' | 'chat' | 'models' | 'settings';
type Message = { id:string; role:'user'|'assistant'; content:string; time:string; stats?:string };
type Chat = { id:string; title:string; pinned:boolean; messages:Message[] };
type Model = { id:string; name:string; path:string; size:string; bytes:number; architecture:string; quantization:string; context:number; status:'ready'|'unsupported'|'missing'; parameterCount?:string; tokenizer:'embedded'|'sidecar'|'missing' };
type Persona = { id:string; name:string; description:string; prompt:string; temperature:number };
type Stats = { cpu_usage:number; memory_used_mb:number; memory_total_mb:number; process_memory_mb:number; gpu_available:boolean; gpu_note:string };
type Gen = { text:string; tokens:number; seconds:number; tokens_per_sec:number; cancelled:boolean };

const personas:Persona[] = [
  {id:'balanced',name:'Balanced',description:'Clear and useful',prompt:'Be clear, useful, concise, and honest.',temperature:.7},
  {id:'coder',name:'Coder',description:'Focused on programming',prompt:'Act as a pragmatic senior programmer. Prefer working code and explain bugs clearly.',temperature:.35},
  {id:'tutor',name:'Tutor',description:'Explains step by step',prompt:'Teach patiently. Start simple, use examples, then add detail when helpful.',temperature:.55},
  {id:'creative',name:'Creative',description:'Ideas and writing',prompt:'Be imaginative, specific, polished, and distinctive.',temperature:.9},
  {id:'researcher',name:'Researcher',description:'Careful and evidence-first',prompt:'Separate facts from assumptions. State uncertainty and never invent sources.',temperature:.35},
  {id:'companion',name:'Companion',description:'Warm conversation',prompt:'Be warm and emotionally aware while staying grounded and honest.',temperature:.78}
];
const starter:Chat = {id:'welcome',title:'Welcome',pinned:true,messages:[]};
const load=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}};
const persist=(key:string,value:unknown)=>localStorage.setItem(key,JSON.stringify(value));
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const clock=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const fmt=(n:number)=>n>=1024**3?`${(n/1024**3).toFixed(2)} GB`:n>=1024**2?`${(n/1024**2).toFixed(1)} MB`:`${Math.max(1,Math.round(n/1024))} KB`;
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const markdown=(s:string)=>esc(s).replace(/\`\`\`([\\s\\S]*?)\`\`\`/g,'<pre>$1</pre>').replace(/\`([^\`]+)\`/g,'<code>$1</code>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br/>');

function App(){
  const [page,setPage]=useState<Page>('home');
  const [dark,setDark]=useState(load('synth.dark',false));
  const [sidebar,setSidebar]=useState(true);
  const [models,setModels]=useState<Model[]>(load('synth.models',[]));
  const [selected,setSelected]=useState(load('synth.selected',''));
  const [people,setPeople]=useState<Persona[]>(load('synth.personas',personas));
  const [personaId,setPersonaId]=useState(load('synth.persona','balanced'));
  const [chats,setChats]=useState<Chat[]>(load('synth.chats',[starter]));
  const [activeId,setActiveId]=useState(load('synth.active','welcome'));
  const [query,setQuery]=useState('');
  const [input,setInput]=useState('');
  const [busy,setBusy]=useState(false);
  const [notice,setNotice]=useState('');
  const [stats,setStats]=useState<Stats|null>(null);
  const [settings,setSettings]=useState(load('synth.settings',{context:4096,temperature:.7,topP:.9,topK:40,repeatPenalty:1.1,maxTokens:512,seed:42}));
  const [personaOpen,setPersonaOpen]=useState(false);
  const [editingPersona,setEditingPersona]=useState<Persona|null>(null);
  const [editId,setEditId]=useState('');
  const [editText,setEditText]=useState('');
  const requestRef=useRef('');

  const active=chats.find(c=>c.id===activeId)||chats[0]||starter;
  const model=models.find(m=>m.id===selected);
  const persona=people.find(p=>p.id===personaId)||people[0];
  const recent=useMemo(()=>chats.filter(c=>c.messages.length&&c.title.toLowerCase().includes(query.toLowerCase())).slice(0,8),[chats,query]);

  useEffect(()=>persist('synth.dark',dark),[dark]);
  useEffect(()=>persist('synth.models',models),[models]);
  useEffect(()=>persist('synth.selected',selected),[selected]);
  useEffect(()=>persist('synth.personas',people),[people]);
  useEffect(()=>persist('synth.persona',personaId),[personaId]);
  useEffect(()=>{persist('synth.chats',chats);persist('synth.active',activeId)},[chats,activeId]);
  useEffect(()=>persist('synth.settings',settings),[settings]);
  useEffect(()=>{const refresh=async()=>{try{setStats(await invoke<Stats>('system_stats'))}catch{}};void refresh();const t=setInterval(refresh,5000);return()=>clearInterval(t)},[]);
  useEffect(()=>{let off:(()=>void)|undefined;listen<{requestId:string;text:string}>('generation-token',e=>{if(e.payload.requestId!==requestRef.current)return;setChats(cs=>cs.map(c=>c.id===activeId?{...c,messages:c.messages.map(m=>m.id===requestRef.current?{...m,content:e.payload.text}:m)}:c))}).then(x=>off=x);return()=>off?.()},[activeId]);
  useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();newChat()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSidebar(true);setQuery('')}if(e.key==='Escape')setPersonaOpen(false)};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[]);

  const toast=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(''),2200)};
  const patch=(fn:(c:Chat)=>Chat)=>setChats(cs=>cs.map(c=>c.id===activeId?fn(c):c));
  function newChat(){const id=uid();setChats(cs=>[{id,title:'New chat',pinned:false,messages:[]},...cs]);setActiveId(id);setPage('chat')}
  async function importModel(){try{const picked=await open({multiple:false,filters:[{name:'GGUF model',extensions:['gguf']}]});if(!picked||Array.isArray(picked))return;const m=await invoke<Model>('inspect_model',{path:String(picked)});setModels(ms=>[m,...ms.filter(x=>x.path!==m.path)]);if(m.status==='ready'){setSelected(m.id);setPage('chat');toast(`${m.name} ready`)}else toast(`${m.name}: ${m.status}`)}catch(e){toast(String(e))}}
  async function attach(){try{const picked=await open({multiple:false,filters:[{name:'Text and code',extensions:['txt','md','json','py','js','jsx','ts','tsx','html','css','rs','toml']}]});if(!picked||Array.isArray(picked))return;const path=String(picked),name=path.split(/[\\\\/]/).pop()||'file';let content='';try{content=await readTextFile(path)}catch{}patch(c=>({...c,messages:[...c.messages,{id:uid(),role:'user',content:`Attached **${name}**${content?' locally.':'.'}`,time:clock()}]}));toast(`${name} attached`)}catch(e){toast(String(e))}}
  async function send(){const text=input.trim();if(!text||busy)return;if(!model){setPage('models');toast('Choose a model first');return}const id=uid();requestRef.current=id;setInput('');setBusy(true);const history=active.messages.slice(-10).map(m=>`${m.role==='user'?'User':'Assistant'}: ${m.content}`).join('\n\n');const prompt=`${persona.prompt}\n\n${history?history+'\n\n':''}User: ${text}\nAssistant:`;patch(c=>({...c,title:c.messages.length?c.title:text.slice(0,48),messages:[...c.messages,{id:uid(),role:'user',content:text,time:clock()},{id,role:'assistant',content:'',time:clock()}]}));try{const r=await invoke<Gen>('start_generation',{request:{requestId:id,modelPath:model.path,prompt,maxTokens:settings.maxTokens,temperature:persona.temperature||settings.temperature,topP:settings.topP,topK:settings.topK,repeatPenalty:settings.repeatPenalty,contextLength:Math.min(Number(model.context||settings.context),Number(settings.context)),seed:settings.seed}});patch(c=>({...c,messages:c.messages.map(m=>m.id===id?{...m,content:r.text,stats:`${r.tokens} tokens · ${r.tokens_per_sec.toFixed(1)} tok/s · ${r.seconds.toFixed(1)}s`}:m)}))}catch(e){patch(c=>({...c,messages:c.messages.map(m=>m.id===id?{...m,content:`**Generation failed**\\n\\n${String(e)}`,stats:'Error'}:m)}))}finally{setBusy(false)}}
  async function createPersona(){const base={id:uid(),name:'My persona',description:'Custom local behavior',prompt:'',temperature:.7};setEditingPersona(base)}
  async function exportPersona(p:Persona){try{const path=await saveDialog({defaultPath:`${p.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.json`,filters:[{name:'JSON',extensions:['json']}]});if(path)await writeTextFile(path,JSON.stringify(p,null,2));toast('Persona exported')}catch(e){toast(String(e))}}
  async function importPersona(){try{const p=await open({multiple:false,filters:[{name:'JSON persona',extensions:['json']}]});if(!p||Array.isArray(p))return;const raw=JSON.parse(await readTextFile(String(p))) as Persona;if(raw.name&&raw.prompt){const x={...raw,id:uid()};setPeople(ps=>[...ps,x]);setPersonaId(x.id);toast('Persona imported')}}catch(e){toast(String(e))}}

  return <div className={dark?'app dark':'app'}>
    {page!=='home'&&<Sidebar open={sidebar} setOpen={setSidebar} search={query} setSearch={setQuery} recent={recent} activeId={activeId} setActiveId={id=>{setActiveId(id);setPage('chat')}} page={page} setPage={setPage} newChat={newChat} models={models} selected={selected}/>}
    <main className={`main ${page==='home'?'main-home':''}`}>
      {page==='home'?<Home models={models} model={model} importModel={importModel} continueChat={()=>setPage('chat')} settings={()=>setPage('settings')}/>:<>
        <header className="topbar"><div className="topbar-left"><button className="icon-btn" onClick={()=>setSidebar(v=>!v)}><Menu size={18}/></button><strong>{page==='models'?'Models':page==='settings'?'Settings':'Chat'}</strong></div><div className="topbar-right"><button className="model-select" onClick={()=>setPage('models')}><Bot size={14}/><span>{model?.name||'No model'}</span><ChevronDown size={13}/></button><button className="icon-btn" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button></div></header>
        {page==='chat'&&<ChatPage active={active} input={input} setInput={setInput} busy={busy} model={model} persona={persona} send={()=>void send()} stop={()=>void invoke('cancel_generation')} attach={()=>void attach()} copy={s=>{void navigator.clipboard?.writeText(s);toast('Copied')}} editId={editId} editText={editText} setEditText={setEditText} beginEdit={m=>{setEditId(m.id);setEditText(m.content)}} saveEdit={id=>{patch(c=>({...c,messages:c.messages.map(m=>m.id===id?{...m,content:editText}:m)}));setEditId('');toast('Message updated')}} cancelEdit={()=>setEditId('')} personaOpen={personaOpen} setPersonaOpen={setPersonaOpen} people={people} setPersonaId={p=>{setPersonaId(p);setPersonaOpen(false)}} createPersona={()=>void createPersona()}/>}
        {page==='models'&&<Models models={models} selected={selected} setSelected={id=>{setSelected(id);setPage('chat')}} importModel={importModel} remove={id=>{setModels(ms=>ms.filter(m=>m.id!==id));if(selected===id)setSelected('')}}/>}
        {page==='settings'&&<SettingsPage dark={dark} setDark={setDark} stats={stats} models={models} selected={selected} setSelected={setSelected} settings={settings} setSettings={setSettings} people={people} setPeople={setPeople} createPersona={()=>void createPersona()} importPersona={()=>void importPersona()} exportPersona={exportPersona}/>}
      </>}
    </main>
    {editingPersona&&<PersonaModal value={editingPersona} setValue={setEditingPersona} close={()=>setEditingPersona(null)} save={()=>{setPeople(ps=>{const i=ps.findIndex(p=>p.id===editingPersona.id);if(i<0)return[...ps,editingPersona];const x=[...ps];x[i]=editingPersona;return x});setPersonaId(editingPersona.id);setEditingPersona(null);toast('Persona saved')}}/>}
    {notice&&<div className="toast"><Check size={14}/>{notice}</div>}
  </div>
}

function Home({models,model,importModel,continueChat,settings}:{models:Model[];model?:Model;importModel:()=>Promise<void>;continueChat:()=>void;settings:()=>void}){
  return <section className="home"><div className="home-top"><Brand/><button className="home-settings" onClick={settings}><Settings size={15}/>Settings</button></div><div className="home-center"><img className="hero-logo" src="/synth-logo.png"/><h1>Welcome to Synth Studio</h1><p>Your local AI studio. Start with a model on your device.</p><div className="model-launch"><button className="launch-model" onClick={()=>void importModel()}><Upload size={16}/><span><strong>{model?.name||'Choose a model'}</strong><small>{model?'Ready on this device':'Import a GGUF model to begin'}</small></span><ChevronDown size={16}/></button>{model&&<button className="continue-btn" onClick={continueChat}>Continue</button>}</div><div className="home-rule"/><div className="home-status"><span><i className={model?'good':''}/>{model?'Model ready':'No model loaded'}</span><span>{models.length} local model{models.length===1?'':'s'}</span><span>Candle · on device</span></div></div></section>
}
function Brand(){return <div className="brand"><img src="/synth-logo.png"/><div><strong>Synth Studio</strong><span>by Fulltrack</span></div></div>}
function Sidebar(p:{open:boolean;setOpen:(b:boolean)=>void;search:string;setSearch:(s:string)=>void;recent:Chat[];activeId:string;setActiveId:(id:string)=>void;page:Page;setPage:(p:Page)=>void;newChat:()=>void;models:Model[];selected:string}){
 if(!p.open)return null;
 return <aside className="sidebar"><div className="sidebar-brand"><Brand/><button className="icon-btn" onClick={()=>p.setOpen(false)}><X size={15}/></button></div><button className="new-chat" onClick={p.newChat}><Plus size={15}/><span>New chat</span><kbd>Ctrl N</kbd></button><div className="searchbox"><Search size={13}/><input value={p.search} onChange={e=>p.setSearch(e.target.value)} placeholder="Search chats"/><kbd>Ctrl K</kbd></div><div className="side-nav"><button className={p.page==='chat'?'active':''} onClick={()=>p.setPage('chat')}><MessageSquare size={15}/>Chat</button><button className={p.page==='models'?'active':''} onClick={()=>p.setPage('models')}><Bot size={15}/>Models</button><button className={p.page==='settings'?'active':''} onClick={()=>p.setPage('settings')}><Settings size={15}/>Settings</button></div><div className="recent-title">Recent</div><div className="recent">{p.recent.length?p.recent.map(c=><button className={c.id===p.activeId?'recent-row active':'recent-row'} key={c.id} onClick={()=>p.setActiveId(c.id)}><History size={12}/><span>{c.title}</span></button>):<span className="recent-empty">No conversations yet</span>}</div><div className="side-bottom"><span className="live-dot"/>Local engine</div></aside>
}
function ChatPage(p:{active:Chat;input:string;setInput:(s:string)=>void;busy:boolean;model?:Model;persona:Persona;send:()=>void;stop:()=>void;attach:()=>void;copy:(s:string)=>void;editId:string;editText:string;setEditText:(s:string)=>void;beginEdit:(m:Message)=>void;saveEdit:(id:string)=>void;cancelEdit:()=>void;personaOpen:boolean;setPersonaOpen:(b:boolean)=>void;people:Persona[];setPersonaId:(id:string)=>void;createPersona:()=>void}){
 const empty=!p.active.messages.length;
 return <section className="chat-page"><div className="chat-scroll">{empty?<div className="chat-welcome"><img src="/synth-logo.png"/><h2>How can I help?</h2><p>{p.model?'Chat locally with '+p.model.name+'.':'Choose a model to start chatting.'}</p></div>:p.active.messages.map(m=><div className={`message ${m.role}`} key={m.id}><div className="msg-avatar">{m.role==='assistant'?<Sparkles size={14}/>:<UserRound size={14}/>}</div><div className="msg-body"><div className="msg-meta"><strong>{m.role==='assistant'?'Synth':'You'}</strong><span>{m.time}</span></div>{p.editId===m.id?<div className="edit-panel"><textarea value={p.editText} onChange={e=>p.setEditText(e.target.value)}/><div><button onClick={p.cancelEdit}>Cancel</button><button className="dark-btn" onClick={()=>p.saveEdit(m.id)}>Save</button></div></div>:<div className="bubble" dangerouslySetInnerHTML={{__html:m.content?markdown(m.content):'<span class="typing"><i></i><i></i><i></i></span>'}}/>}<div className="msg-actions"><button onClick={()=>p.copy(m.content)}><Copy size={11}/>Copy</button>{m.role==='user'&&<button onClick={()=>p.beginEdit(m)}>Edit</button>}{m.stats&&<span>{m.stats}</span>}</div></div></div>)}</div><div className="composer-wrap"><div className="composer"><textarea value={p.input} disabled={p.busy} onChange={e=>p.setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();p.send()}}} placeholder={p.model?'Message Synth…':'Choose a model to start…'}/><div className="composer-row"><button className="tool-btn" onClick={p.attach}><Paperclip size={15}/></button><div className="persona-wrap"><button className="persona-btn" onClick={()=>p.setPersonaOpen(!p.personaOpen)}><Sparkles size={13}/>{p.persona.name}<ChevronDown size={12}/></button>{p.personaOpen&&<div className="persona-menu">{p.people.map(x=><button key={x.id} onClick={()=>p.setPersonaId(x.id)}><span><strong>{x.name}</strong><small>{x.description}</small></span>{x.id===p.persona.id&&<Check size={13}/>}</button>)}<div className="persona-divider"/><button onClick={p.createPersona}><Plus size={13}/><span><strong>Create persona</strong><small>Custom local behavior</small></span></button></div>}</div><span className="composer-state"><i className="live-dot"/> {p.model?.name||'No model'}</span>{p.busy?<button className="send stop" onClick={p.stop}><span/>Stop</button>:<button className="send" disabled={!p.input.trim()||!p.model} onClick={p.send}><Send size={14}/></button>}</div></div><p className="local-note">Local-first · Conversations and models stay on this device.</p></div></section>
}
function Models({models,selected,setSelected,importModel,remove}:{models:Model[];selected:string;setSelected:(id:string)=>void;importModel:()=>Promise<void>;remove:(id:string)=>void}){
 return <section className="content"><div className="content-head"><div><span className="eyebrow">LOCAL LIBRARY</span><h1>Models</h1><p>Only imported models appear here. No sample or fake models.</p></div><button className="primary" onClick={()=>void importModel()}><Upload size={14}/>Import GGUF</button></div>{!models.length?<div className="empty-models"><img src="/synth-logo.png"/><h3>No models installed</h3><p>Import a GGUF model from your computer. Synth will inspect it before making it available.</p><button className="secondary" onClick={()=>void importModel()}><FilePlus2 size={14}/>Import a model</button></div>:<div className="model-list">{models.map(m=><article className={selected===m.id?'model-row selected':'model-row'} key={m.id}><div className="model-icon"><Bot size={18}/></div><div className="model-main"><div className="model-name"><strong>{m.name}</strong><span className={m.status==='ready'?'ready':m.status==='unsupported'?'warn':''}><i/> {m.status==='ready'?'Ready':m.status==='missing'?'Tokenizer needed':'Unsupported'}</span></div><div className="model-path">{m.path}</div><div className="model-tags"><span>{m.size}</span><span>{m.quantization}</span><span>{m.architecture}</span><span>Context {m.context}</span></div></div><div className="model-actions">{m.status==='ready'&&<button className="use-btn" onClick={()=>setSelected(m.id)}>{selected===m.id?<><Check size={13}/>Active</>:<>Use</>}</button>}<button className="icon-btn" title="Remove" onClick={()=>remove(m.id)}><Trash2 size={14}/></button></div></article>)}</div>}</section>
}
function SettingsPage(p:{dark:boolean;setDark:(b:boolean)=>void;stats:Stats|null;models:Model[];selected:string;setSelected:(s:string)=>void;settings:any;setSettings:(s:any)=>void;people:Persona[];setPeople:(p:Persona[])=>void;createPersona:()=>void;importPersona:()=>void;exportPersona:(p:Persona)=>void}){
 return <section className="content settings-page"><div className="content-head"><div><span className="eyebrow">PREFERENCES</span><h1>Settings</h1><p>Simple controls for your local workspace.</p></div></div><SettingRow title="Theme" desc="Light is the default and keeps the interface minimal."><div className="segmented"><button className={!p.dark?'selected':''} onClick={()=>p.setDark(false)}><Sun size={13}/>Light</button><button className={p.dark?'selected':''} onClick={()=>p.setDark(true)}><Moon size={13}/>Dark</button></div></SettingRow><SettingRow title="Default model" desc="Model used when a new chat starts."><select value={p.selected} onChange={e=>p.setSelected(e.target.value)}><option value="">None</option>{p.models.filter(m=>m.status==='ready').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></SettingRow><SettingRow title="Generation" desc="These defaults are used when Synth generates a response."><div className="generation-grid"><Range label="Temperature" value={p.settings.temperature} min={0} max={1.2} step={.01} change={v=>p.setSettings({...p.settings,temperature:v})}/><Range label="Top P" value={p.settings.topP} min={.1} max={1} step={.01} change={v=>p.setSettings({...p.settings,topP:v})}/><Range label="Top K" value={p.settings.topK} min={1} max={100} step={1} change={v=>p.setSettings({...p.settings,topK:v})}/><Range label="Max tokens" value={p.settings.maxTokens} min={32} max={2048} step={32} change={v=>p.setSettings({...p.settings,maxTokens:v})}/></div></SettingRow><SettingRow title="Personas" desc="Built-in and custom behavior profiles."><div className="persona-settings">{p.people.map(x=><div key={x.id}><span><strong>{x.name}</strong><small>{x.description}</small></span><button className="mini" onClick={()=>p.exportPersona(x)}><Download size={12}/></button></div>)}<div className="persona-settings-actions"><button className="secondary" onClick={p.createPersona}><Plus size={13}/>Create</button><button className="secondary" onClick={p.importPersona}><Upload size={13}/>Import</button></div></div></SettingRow><SettingRow title="System" desc="Live host information from the Rust backend."><div className="system-grid"><div><small>CPU</small><strong>{p.stats?Math.round(p.stats.cpu_usage):'—'}%</strong></div><div><small>RAM</small><strong>{p.stats?Math.round(p.stats.memory_used_mb):'—'} MB</strong></div><div><small>App</small><strong>{p.stats?Math.round(p.stats.process_memory_mb):'—'} MB</strong></div><div><small>GPU</small><strong>{p.stats?.gpu_available?'Available':'CPU'}</strong></div></div></SettingRow><div className="privacy"><Check size={14}/><div><strong>Local-first</strong><span>No account, no cloud inference, no hosted chat history.</span></div></div></section>
}
function SettingRow({title,desc,children}:{title:string;desc:string;children:ReactNode}){return <div className="setting-row"><div><strong>{title}</strong><span>{desc}</span></div>{children}</div>}
function Range(p:{label:string;value:number;min:number;max:number;step:number;change:(n:number)=>void}){return <label className="range"><span>{p.label}<b>{p.value}</b></span><input type="range" min={p.min} max={p.max} step={p.step} value={p.value} onChange={e=>p.change(Number(e.target.value))}/></label>}
function PersonaModal({value,setValue,close,save}:{value:Persona;setValue:(p:Persona)=>void;close:()=>void;save:()=>void}){return <div className="scrim"><div className="modal"><div className="modal-head"><div><span className="eyebrow">PERSONA</span><h2>{value.name}</h2></div><button className="icon-btn" onClick={close}><X size={15}/></button></div><label>Name<input value={value.name} onChange={e=>setValue({...value,name:e.target.value})}/></label><label>Description<input value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></label><label>Instructions<textarea value={value.prompt} onChange={e=>setValue({...value,prompt:e.target.value})}/></label><Range label="Temperature" value={value.temperature} min={0} max={1.2} step={.01} change={v=>setValue({...value,temperature:v})}/><div className="modal-actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={save}>Save persona</button></div></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
